platform :ios, '8.0'

use_frameworks!

target ‘DolphinFinancial' do

pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'MBProgressHUD'
#  pod 'IQKeyboardManager'
pod 'YYModel'
pod 'MJRefresh'

pod 'Charts'

end
